[package]
name = "channelizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.7"
num = "0.4"
rustfft = "6.1.0"
rayon = "1.7.0"
queues = "1.1.0"
circular-buffer = "0.1.3"
