[package]
name = "offline_channelizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
libm = "0.2.7"
scilib = "1.0.0"

[build-dependencies]
cc = "1.0"
