[package]
name = "offlinepfb-sys"
version = "0.1.0"
edition = "2021"
links = "offlinepfb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.83"

[dependencies]
libm = "0.2.8"
num = "0.4.1"
